include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "templates/**"
    - "packages/genrevibes_starter_kit/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
